### ISSUE TITLE
npm presence

### ISSUE THREAD

**Issue by marekhrabe** [mateodelnorte/coinbase#19]
Is this package published on npm? From your `package.json` it looks like it should map to [coinbase](https://www.npmjs.com/package/coinbase) package, but in the npm registry there is a different package with that name already (the official one). Would you mind publishing this one with a different name, so users can depend on this package by npm name instead of github remote?

**Comment by mateodelnorte** [comment]
This package is published under the `coinbase` package's 0.1.X version numbers. If you do an `npm install coinbase@0.1.4`, you will get this package. 

I wrote this package before coinbase offered any official node wrapper for their api. Since creating one, they reached out and asked if they could use the name going forward. At that point, we pointed the module's repo property to the new repository, under their name.
